### PR TITLE
Add option to mark selected page in header.inc

### PR DESCRIPTION
**Pull request by Aaron-Junker**
This mimics the behaviour of www.php.net.

It currently adds this behaviour to the qa page.

### CODE REVIEW

**Comment by Aaron-Junker** [comment]
@cmb69 what do I have to do that someone will review this.

**Review by cmb69 — COMMENTED** [review]
Hmm, it looks like all these variables don't really work; e.g. `$TITLE` is almost always `Quality Assurance` for web-qa for me, except for those pages where it is explicitly passed to `common_header()`. Apparently, that has been broken with some "refactoring". I suggest to focus on that first, before introducing more of these variables.

**Comment by Aaron-Junker** [comment]
image.

This is now fixed.

**Comment by Aaron-Junker** [comment]
@cmb69

**Comment by cmb69** [comment]
Ah, now I see. Thanks! I think this is okay (I left a comment on the web-qa PR, though), but I really think that we should clean up that terrible code before proceeding with more features.

**Comment by Aaron-Junker** [comment]
> Ah, now I see. Thanks! I think this is okay (I left a comment on the web-qa PR, though)

@cmb69 This is now fixed. 

> but I really think that we should clean up that terrible code before proceeding with more features.

This may be something I will look into in the future (maybe backport changes from web-php to here. See also php/web-php#523). But in my opionion this should not block merging this PR.

**Review by cmb69 — APPROVED** [review]
Thank you! Looks good to me now.

> But in my opionion this should not block merging this PR.

Right. It's just that I want to avoid further improvements, before we have the code cleaned up; at least a bit.

**Pull request closed without merging**
