### PR TITLE
Fix footer background and borders

### PR DESCRIPTION
**Pull request by marjadej**
## Before
screen shot 2017-10-08 at 20 00 44

## After
screen shot 2017-10-08 at 20 02 06

(random ping) @morrisonlevi  Please review :-)

### CODE REVIEW

**Comment by p-h-p** [comment]
@morrisonlevi True, I forgot to zoom-out really good, will fix. Thanks.

**Comment by salathe** [comment]
This patch looks odd when I try it out (see below).  If I undo your changes except for the background color for `footer nav.fullscreen`, then it looks good.

screen shot 2017-10-09 at 21 44 18

**Comment by petk** [comment]
Hello, this has been now applied via 72d41647d22331119566f881240cc957dc451e57

with adjustment by only changing the background on the `footer nav.fullscreen` element.  In case of issues, report back. Thanks...

**Comment by php-pulls** [comment]
**Comment on behalf of petk at php.net:**

Applied via 72d41647d22331119566f881240cc957dc451e57

**Pull request closed without merging**
